### ISSUE TITLE
Investigate whether we should zero margin/padding in :before & :after

### ISSUE THREAD

**Issue by iteles** [dwyl/tudo#109]
Currently we've added some zeroing of margins and padding into the `*, *:before, *:after {}` block, in the form of:

``` css
*, *:before, *:after {
  box-sizing: inherit;
  margin: inherit;
  padding: inherit;
}
```

Is this best practice or should they be standalone against specific selectors?
